### ISSUE TITLE
Throws exception in Rider 2024.2.1

### ISSUE THREAD

**Issue by Mason32NZ** [chylex/IntelliJ-Colored-Brackets#1]
After upgrading from 2024.1.X to 2024.2.1 Rider through the following error:

```
java.lang.Throwable: com.github.izhangzhihao.rainbow.brackets.BracePairs <clinit> requests com.intellij.codeInsight.highlighting.FileTypeBraceMatcher instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.codeInsight.highlighting.FileTypeBraceMatcher.getInstance(FileTypeBraceMatcher.java:11)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcherByFileType(BraceMatchingUtil.java:470)
	at com.intellij.codeInsight.highlighting.BraceMatchingUtil.getBraceMatcher(BraceMatchingUtil.java:444)
	at com.github.izhangzhihao.rainbow.brackets.BracePairs.<clinit>(BracePairs.kt:29)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor$Companion.filterPairs(DefaultRainbowVisitor.kt:241)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor$Companion.access$filterPairs(DefaultRainbowVisitor.kt:47)
	at com.github.izhangzhihao.rainbow.brackets.visitor.DefaultRainbowVisitor.visit(DefaultRainbowVisitor.kt:20)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitor(HighlightVisitorRunner.java:194)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$3(HighlightVisitorRunner.java:122)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:120)
	at com.intellij.concurrency.client.ClientIdPropagation.captureClientIdInProcessor$lambda$7(ClientIdPropagation.kt:63)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

Though the brackets are still colored so it seems to still be working.

**Comment by chylex** [comment]
I'll look into it today, thanks.

I have renamed the project and am restructuring the fork to try to upload it to JetBrains Marketplace, so it's easier for people who just want the old version with CLion/Rider support, and possibly some small improvements.

**Comment by chylex** [comment]
You can uninstall the old version and install https://plugins.jetbrains.com/plugin/25980-colored-brackets instead.

If you'd like to keep your settings, find the IDE settings folder (for ex. `%APPDATA%\JetBrains\Rider2024.3`), go to `options`, rename `rainbow_brackets.xml` to `colored_brackets.xml`, and replace the first two lines with:

```xml
<application>
  <component name="ColoredBracketsSettings">
```
